(add-to-list 'auto-mode-alist '("\.trig$" . plsql-mode))
(add-to-list 'auto-mode-alist '("\.pkg$" . plsql-mode))
(add-to-list 'auto-mode-alist '("\.proc$" . plsql-mode))
(add-to-list 'auto-mode-alist '("\.vws$" . sql-mode))
(add-to-list 'auto-mode-alist '("\.pp$" . puppet-mode))
(add-to-list 'auto-mode-alist '("\.md$" . markdown-mode))
