;;; mermaid-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mermaid-ts-mode.el

(autoload 'mermaid-ts-mode "mermaid-ts-mode" "\


(fn)" t)
(register-definition-prefixes "mermaid-ts-mode" '("mermaid-ts-"))

;;; End of scraped data

(provide 'mermaid-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mermaid-ts-mode-autoloads.el ends here
