;;; lorem-ipsum-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lorem-ipsum.el

(autoload 'lorem-ipsum-use-default-bindings "lorem-ipsum" "\
Use the default keybindings of `C-c l [spl]'.")
(autoload 'lorem-ipsum-insert-paragraphs "lorem-ipsum" "\
Insert lorem ipsum paragraphs into buffer.
If NUM is non-nil, insert NUM paragraphs.

(fn &optional NUM)" t)
(autoload 'lorem-ipsum-insert-sentences "lorem-ipsum" "\
Insert lorem ipsum sentences into buffer.
If NUM is non-nil, insert NUM sentences.

(fn &optional NUM)" t)
(autoload 'lorem-ipsum-insert-list "lorem-ipsum" "\
Insert lorem ipsum list items into buffer.
If NUM is non-nil, insert NUM list items.

(fn &optional NUM)" t)
(define-obsolete-function-alias 'Lorem-ipsum-insert-paragraphs 'lorem-ipsum-insert-paragraphs "29.1")
(define-obsolete-function-alias 'Lorem-ipsum-insert-sentences 'lorem-ipsum-insert-sentences "29.1")
(define-obsolete-function-alias 'Lorem-ipsum-insert-list 'lorem-ipsum-insert-list "29.1")
(register-definition-prefixes "lorem-ipsum" '("lorem-ipsum-"))

;;; End of scraped data

(provide 'lorem-ipsum-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lorem-ipsum-autoloads.el ends here
